[pyprland]
plugins = [
  "scratchpads",
  "magnify",
  "expose",
  "shortcuts_menu",
  "toggle_special",
  "wallpapers"
]

[scratchpads.volume]
command = "pwvucontrol --class volume_sidemenu"
animation = "fromLeft"
class = "volume_sidemenu"
size = "40% 70%"
unfocus = "hide"
excludes = "*"
lazy = true
margin = 90
multi = false

[shortcuts_menu.entries]
"Color picker" = [
    {name="format", options=["hex", "rgb", "hsv", "hsl", "cmyk"]},
    "sleep 0.2; hyprpicker --format [format] -a" # sleep to let the menu close before the picker opens
]

[wallpapers]
unique = true # set a different wallpaper for each screen
path = "~/Pictures/i3_wallpapers/"
interval = 15 # change every 15 minutes
extensions = ["jpg", "jpeg", "png"]
recurse = true
## Using swww
command = 'swww img --resize crop --transition-type random "[file]"'
clear_command = "swww clear"
